# Generic makefile - Unix (sgi) version
#
             SHELL = /bin/sh
            LDLIBS = -lMrm -lXm_s -lXt_s -lX11_s -lPW -lmalloc 
         LDOPTIONS = 
            CFLAGS = -O2 -prototypes -cckr -float -I/usr/include $(DEFINES) -DSYSV -DMALLOC_0_RETURNS_NULL -DFUNCPROTO -DNARROWPROTO 
                RM = rm -f

include CommonMakefile

$(PGM):: $(OBJS) 
	$(RM) $@
	$(CC) -o $@ $(OBJS) $(LDOPTIONS) $(LDLIBS)
